export const descData = [
  {
    property: 'title',
    type: 'string',
    default: '-',
    optionValues: '-',
    explain: '标题',
  },
  {
    property: 'size',
    type: 'string',
    default: 'small',
    optionValues: '-',
    explain: '大小',
  },
  {
    property: 'bordered',
    type: 'boolean',
    default: 'true',
    optionValues: '-',
    explain: '是否展示边框',
  },
  {
    property: 'column',
    type: 'Number, Object',
    default: ' Object	{ xxl: 4, xl: 3, lg: 3, md: 3, sm: 2, xs: 1 }',
    optionValues: '-',
    explain: '一行的 DescriptionItems 数量',
  },
  {
    property: 'useCollapse',
    type: 'boolean',
    default: ' -',
    optionValues: '-',
    explain: '是否包裹 CollapseContainer 组件',
  },
  {
    property: 'collapseOptions',
    type: 'Object',
    default: ' -',
    optionValues: '-',
    explain: 'CollapseContainer 组件属性',
  },
  {
    property: 'schema',
    type: 'DescItem[]',
    default: ' -',
    optionValues: '-',
    explain: '详情项配置，见下方 schema 配置',
  },
  {
    property: 'data',
    type: 'any',
    default: ' -',
    optionValues: '-',
    explain: '数据源',
  },
];

export const schemaData = [
  {
    property: 'field',
    type: 'string',
    default: '-',
    optionValues: '-',
    explain: '字段名',
  },
  {
    property: 'label',
    type: 'string',
    default: '-',
    optionValues: '-',
    explain: '标签名',
  },
  {
    property: 'labelMinWidth',
    type: 'number',
    default: '-',
    optionValues: '-',
    explain: 'label 最小宽度',
  },
  {
    property: 'contentMinWidth',
    type: 'number',
    default: '-',
    optionValues: '-',
    explain: 'content 最小宽度',
  },
  {
    property: 'labelStyle',
    type: 'any',
    default: '-',
    optionValues: '-',
    explain: 'label 样式',
  },
  {
    property: 'span',
    type: 'number',
    default: '-',
    optionValues: '-',
    explain: '和并列数量',
  },
  {
    property: 'show',
    type: '(data)=>boolean',
    default: '-',
    optionValues: '-',
    explain: '动态判断当前组件是否显示',
  },
  {
    property: 'render',
    type: '(val: string, data: any)=>VNode | undefined | Element | string | number;',
    default: '-',
    optionValues: '-',
    explain: '自定义渲染 content',
  },
];
